[tools]
lefthook = "2.0.12"

# lefthook hooks
actionlint = "1.7.9"
"npm:@commitlint/cli" = "20.2.0"
"npm:prettier" = "3.7.4"
"cargo:basefmt" = "0.1.0"
shellcheck = "0.11.0"
shfmt = "3.12.0"

[settings]
npm.bun = true
